### ISSUE TITLE
use kube.rs dns before release

### ISSUE THREAD

**Issue by clux** [kube-rs/website#2]
currently we have the standard github pages address setup: https://kube-rs.github.io/website/

we will need to:

- change kube.rs domain to point
- possibly change some cname configuration to ensure the urls inside the project use kube.rs

keep struggling to do this, so any help here is possible.
think we need to go through the CNCF helpdesk with the domain if it's been transferred away from us @teozkr

(task list by @teozkr;)
- [X] Add domain to repo settings
- [X] Request change from CNCF
- [x] Receive confirmation of change from CNCF
- [x] Update repo website link
- [X] Update Discord website link
- [X] Publish website repo

**Comment by teozkr** [comment]
Okay, it should all be sorted now then.

**Comment by clux** [comment]
Beautiful! Thanks a lot!
