### ISSUE TITLE
Typos in server-side apply snippet

### ISSUE THREAD

**Issue by jmintb** [kube-rs/website#25]
The following snippet in the [docs](https://kube.rs/controllers/reconciler/#in-depth-solution) seems to be incorrect.

```rust
let pod = pods.create(pod.name(), serversideapply, Patch::Apply(pod_data)).await?
```

I think it should be something like: 
```rust
let pod = pods.patch(pod.name(), PatchParams::apply("myfieldmanager"), Patch::Apply(pod_data)).await?
```

I also stumbled upon a few other typos in the documentation code snippets, this one just confused me the most haha.

Are the docs in a state where it makes sense to submit PRs for something like this? I ask because the docs still seem to be in the early stages of development(based on the other issues for this repo) and I can't tell what will change and what will stay.

I enjoyed going through the docs, good stuff :+1:

**Comment by kazk** [comment]
We should be able to accept PRs for typos.

/cc @clux You probably didn't get the notification because you're not watching this repo.

**Comment by clux** [comment]
Yeah, contributions welcome (even if it's just typos). I will go through at some point and modernise the overarching setup and complete more, but there are some rather large pieces on kube i want to get done first (client v2).

Watching the repo now 😅

**Comment by clux** [comment]
btw I think i wrote `serversideapply` there as a var because it's a common one in the kube/examples directory, but it's definitely unclear here.

**Comment by jmintb** [comment]
Awesome!
> We should be able to accept PRs for typos.

I see that makes sense haha :+1: 
> btw I think i wrote `serversideapply` there as a var because it's a common one in the kube/examples directory, but it's definitely unclear here.
