### ISSUE TITLE
little typo in docs/controllers/object.md

### ISSUE THREAD

**Issue by p-alik** [kube-rs/website#46]
There is a little typo `s/tthe/the/` in the sentence `We have to recursively re-implement every part of [Pod] that we care about, but we automatically drop every field except tthe ones we defined. ` at the end of the section [Partially-typed Resource](https://github.com/kube-rs/website/blob/main/docs/controllers/object.md#partially-typed-resource).

**Comment by clux** [comment]
Thanks!
